# Generated by Django 3.0.2 on 2020-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(blank=True, max_length=191, null=True)),
                ('ContactName', models.CharField(blank=True, max_length=191, null=True)),
                ('ContactTitle', models.CharField(blank=True, max_length=191, null=True)),
                ('Address', models.TextField(blank=True, help_text='Please provide address')),
                ('City', models.CharField(blank=True, max_length=191, null=True)),
                ('Region', models.CharField(blank=True, max_length=191, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=191, null=True)),
                ('Country', models.CharField(blank=True, max_length=191, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('Fax', models.CharField(blank=True, max_length=191, null=True)),
                ('HomePage', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ('created_at',),
            },
        ),
    ]
