# Generated by Django 3.0.2 on 2020-01-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(blank=True, max_length=191, null=True)),
                ('Description', models.TextField(blank=True, help_text='Please provide a description of this category')),
                ('Picture', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(blank=True, max_length=191, null=True)),
                ('QuantityPerUnit', models.PositiveIntegerField(blank=True, null=True)),
                ('UnitPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('UnitsInStock', models.PositiveIntegerField(blank=True, null=True)),
                ('UnitisOnOrder', models.PositiveIntegerField(blank=True, null=True)),
                ('ReorderLevel', models.IntegerField(blank=True, null=True)),
                ('Discontinued', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CategoryID', models.ManyToManyField(blank=True, related_name='categories', to='whmanager.Categories')),
                ('SupplierID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id', to='whmanager.Suppliers')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('UnitPrice', models.CharField(max_length=191)),
                ('Quanity', models.CharField(max_length=191)),
                ('Discount', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ProductID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='whmanager.Products')),
            ],
            options={
                'db_table': 'order_details',
                'ordering': ('created_at',),
            },
        ),
    ]
